- name: Ensure netconf is running
  vars:
    ansible_connection: network_cli
  junipernetworks.junos.junos_netconf:

- name: Backup junos configuration
  vars:
    ansible_connection: netconf
  junipernetworks.junos.junos_config:
    backup: true
  register: config_output

- name: Print config backup
  ansible.builtin.debug:
    msg: "{{ config_output }}"
