- name: Ensure netconf is running
  vars:
    ansible_connection: network_cli
  junipernetworks.junos.junos_netconf:

- name: Backup junos configuration
  vars:
    ansible_connection: netconf
  junipernetworks.junos.junos_config:
    backup: true
    backup_options:
      dir_path: /tmp/
      filename: "{{ inventory_hostname }}.txt"
  register: config_output
- name: Show the backup in debug message
  ansible.builtin.debug:
     msg: "backup  {{ config_output }}"
    
    
