---
- name: Retrieve network configurations
  hosts: network
  gather_facts: false

  tasks:


    - name: Backup configuration
      ansible.builtin.include_role:
        name: "../roles/backup"
      when: ansible_network_os is defined


